server:
  port: 8080

routines:
  path: data
  file-one: one.txt
  file-two: two.txt

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/h2
  datasource:
    hikari:
      connectionTestQuery: SELECT 1
      minIdle: 1
      maxPoolSize: 10
      poolName: pool
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:claro;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2.console.enabled: true
  jackson.default-property-inclusion: NON_EMPTY

logging.level.root: INFO